spring.application.index: ${random.uuid} # this ensures that our applicationId is unique
spring:
  cloud:
    stream:
      artemis:
        binder:
          transport: org.apache.activemq.artemis.core.remoting.impl.netty.NettyConnectorFactory
          host: localhost
          port: 61616